config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resource :twitter_settings, :only => ['show', 'update', 'edit']
  end
end

app/models/spree/product_decorator.rb
module Spree
  Product.class_eval do 
    has_one :hashtags, class_name: 'Spree::Twitter::Hashtag', 
      :foreign_key => "value", 
      :primary_key => "hashtag"

    has_many :tweets, through: :hashtags, class_name: 'Spree::Twitter::Tweet',
      :order => 'created_at DESC'

    before_save :assign_hashtag

    private

    def assign_hashtag
      hashtag = master.sku if hashtag.blank?
    end
  end
end

app/models/spree/twitter.rb
module Spree::Twitter
  def self.table_name_prefix
    'spree_twitter_'
  end
end

app/models/spree/twitter/hashtag.rb
module Spree
  module Twitter
    class Hashtag < ActiveRecord::Base
      has_and_belongs_to_many :tweets, 
        join_table: :spree_twitter_hashtags_spree_twitter_tweets,
        foreign_key: :spree_twitter_hashtag_id, 
        association_foreign_key: :spree_twitter_tweet_id 
        
      validates_presence_of :value

    end
  end
end

app/models/spree/twitter/tweet.rb
module Spree
  module Twitter
    class Tweet < ActiveRecord::Base
      has_and_belongs_to_many :hashtags, 
        join_table: :spree_twitter_hashtags_spree_twitter_tweets,
        association_foreign_key: :spree_twitter_hashtag_id, 
        foreign_key: :spree_twitter_tweet_id 

      after_create :populate_hashtags
      serialize :attrs, Hash

      def user
        OpenStruct.new attrs_hash[:user] 
      end

      def medias
        return [] if attrs_hash[:entities][:media].nil?
        attrs_hash[:entities][:media].map{ |x| OpenStruct.new(x) } unless attrs_hash[:entities][:media].nil?
      end

      def text
        attrs_hash[:text]
      end

      def fulltext; text end

      def urls
        obj = []

        attrs_hash[:entities][:urls].each do |url|
          obj << {
            url: url[:url],
            display: url[:display_url]
          }
        end
        obj
      end

      def markups_and_positions
        obj = []
        
        attrs_hash[:entities][:hashtags].each do |hashtag|
          obj << {
            val: '</a>',
            pos: hashtag[:indices][1]
          }

          obj << {
            val: self.class.url_hashtag_start(hashtag[:text]),
            pos: hashtag[:indices][0]
          }
        end unless attrs_hash[:entities][:hashtags].nil?

        attrs_hash[:entities][:user_mentions].each do |user_mentions|
          obj << {
            val: '</a>',
            pos: user_mentions[:indices][1]
          }

          obj << {
            val: self.class.url_mention_start(user_mentions[:screen_name]),
            pos: user_mentions[:indices][0]
          }
        end unless attrs_hash[:entities][:user_mentions].nil?

        attrs_hash[:entities][:urls].each do |url|
          obj << {
            val: '</a>',
            pos: url[:indices][1]
          }

          obj << {
            val: self.class.url_start(url[:url]),
            pos: url[:indices][0]
          }
        end unless attrs_hash[:entities][:urls].nil?

         attrs_hash[:entities][:media].each do |media|
          obj << {
            val: '</a>',
            pos: media[:indices][1]
          }

          obj << {
            val: self.class.url_start(media[:expanded_url]),
            pos: media[:indices][0]
          }
        end unless attrs_hash[:entities][:media].nil?

        obj.sort{|x,y| y[:pos] <=> x[:pos]}
      end

      def initialize_twitter_connection
        @twitter_config = Spree::TwitterConfiguration.new
        @client = Twitter::REST::Client.new do |config|
          config.consumer_key        = @twitter_config.consumer_key
          config.consumer_secret     = @twitter_config.consumer_secret
          config.access_token        = @twitter_config.access_token
          config.access_token_secret = @twitter_config.access_token_secret
        end
      end

      def favorite_count 
        attrs_hash[:favorite_count]
      end
      
      def self.url_hashtag_start(tag)
        "<a href='http://twitter.com/search?q=%23#{tag}' class='hashtag-link' target='_blank'>"
      end

      def self.url_start(url)
        "<a href='http://#{url}' class='twitter-url' target='_blank'>"
      end

      def self.url_mention_start(screen_name)
        "<a href='http://twitter.com/#{screen_name}' class='mention-link' target='_blank'>"
      end

      private 

      def attrs_hash
        if attrs.class == String
          return eval(attrs)
        elsif attrs.class == Hash
          return attrs
        end
      end

      def populate_hashtags
        attrs_hash[:entities][:hashtags].each do |hashtag|
          hashtag = Spree::Twitter::Hashtag.find_or_create_by(value: hashtag[:text])
          hashtags << hashtag unless hashtags.include? hashtag
        end
      end
    end
  end
end

app/controllers/spree/admin/twitter_settings_controller.rb
module Spree
  module Admin
    class TwitterSettingsController < Spree::Admin::BaseController

      def edit
        @preferences = [:consumer_key, :consumer_secret, :access_token, :access_token_secret]
        @config = Spree::TwitterConfiguration.new
      end

      def update
        config = Spree::TwitterConfiguration.new

        params.each do |name, value|
          next unless config.has_preference? name
          config[name] = value
        end

        redirect_to edit_admin_twitter_settings_path
      end
    end
  end
end

app/helpers/spree/admin/twitter_settings_controller_helper.rb
module Spree::Admin::TwitterSettingsControllerHelper
end

app/helpers/spree/base_helper_decorator.rb
module Spree
    BaseHelper.class_eval do 
    def format_tweet(tweet)
      text = tweet.text
      # tweet.urls.each do |url|
      #   text.gsub!(url[:url], url[:display])
      # end
      # puts "Tweet is now |#{text}|"


      tweet.markups_and_positions.each do |item|
        text.insert(item[:pos], item[:val])
      end

      tweet.urls.each do |url|
        text.gsub!(url[:url], url[:display])
      end
      puts "Tweet is now |#{text}|"

      text
    end
  end
end

app/views/spree/admin/twitter_settings/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:twitter_settings) %>
<% end %>

<%= form_tag admin_twitter_settings_path, :method => :put  do |form| %>
  <div id="preferences" data-hook>
    <fieldset class="general no-border-top">
      <div class="row">
        <div class="alpha twelve columns">
          <fieldset class="security no-border-bottom">
            <legend align="center"><%= Spree.t(:twitter)%></legend>
            <% @preferences.each do |key|
                type = @config.preference_type(key) %>
                <div class="field">
                  <%= label_tag(key, Spree.t(key) + ': ') + tag(:br) if type != :boolean %>
                  <%= preference_field_tag(key, @config[key], :type => type) %>
                  <%= label_tag(key, Spree.t(key)) + tag(:br) if type == :boolean %>
                </div>
            <% end %>
          </fieldset>
        </div>
      </div>

      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button Spree.t(:update), 'icon-refresh' %>
        <span class="or"><%= Spree.t(:or) %></span>
        <%= link_to_with_icon 'icon-remove', Spree.t(:cancel), edit_admin_twitter_settings_url, :class => 'button' %>
      </div>

    </fieldset>
  </div>
<% end %>

app/views/spree/shared/_product_twitter_feed.html.erb
<% unless @product.tweets.empty? %>
<div class='twitter-feed'>
<ul>
<% @product.tweets.each do |tweet| %>
    <li class='tweet clearfix clear container'>
      <div class='avatar col-xs-3'>
        <img src="<%=tweet.user.profile_image_url %>">
      </div>
      <div class='tweet-content col-xs-9'>
        <div class='tweet-header'>
        <%= link_to "http://twitter.com/#{tweet.user.screen_name}" do %>
          <span class='name'><%= tweet.user.name %></span> <span class='nickname'>@<%= tweet.user.screen_name %></span>
        <% end %>
          <!-- 26m -->
        </div>
          <p>
            <%=  format_tweet(tweet).html_safe %>
          </p>
          <% unless tweet.medias.empty? %>
            <ul class='tweet-images text-center'>
              <% tweet.medias.each do |media| %>
                <li><%= link_to image_tag("#{media.media_url}:thumb"),  media.url, target: '_blank' %></li>
              <% end %>
            </ul>
          <% end %>
        <div class='tweet-footer text-right'>
          <i class='glyphicon glyphicon-retweet'></i> <%= tweet.retweet_count %>  
          <i class='glyphicon glyphicon-star'></i> <%= tweet.favorite_count %>  
        </div>
      </div>
      
    </li>
<% end %>
</ul>
</div>
<% end %>